//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kataraktaCS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("kataraktaCS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AboutWindowArt {
            get {
                object obj = ResourceManager.GetObject("AboutWindowArt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Folder Settings.
        /// </summary>
        internal static string buttonCreateFolderSettings {
            get {
                return ResourceManager.GetString("buttonCreateFolderSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Template.
        /// </summary>
        internal static string buttonCreateTemplate {
            get {
                return ResourceManager.GetString("buttonCreateTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Folder Settings.
        /// </summary>
        internal static string buttonRemoveFolderSettings {
            get {
                return ResourceManager.GetString("buttonRemoveFolderSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Template.
        /// </summary>
        internal static string buttonRemoveTemplate {
            get {
                return ResourceManager.GetString("buttonRemoveTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm_Title {
            get {
                return ResourceManager.GetString("Confirm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you would like to fix the textures&apos; borders? This change won&apos;t be harmful, but it can&apos;t be undone, so please confirm..
        /// </summary>
        internal static string ConfirmTextureBorders {
            get {
                return ResourceManager.GetString("ConfirmTextureBorders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not register a hotkey. Please make sure that you don&apos;t have the same hotkey set to multiple textures..
        /// </summary>
        internal static string Error_CouldNotRegisterHotkey {
            get {
                return ResourceManager.GetString("Error_CouldNotRegisterHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid cache file: specified length of the texture is longer than the rest of the cache file..
        /// </summary>
        internal static string Error_InvalidCache {
            get {
                return ResourceManager.GetString("Error_InvalidCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to read this folder settings file. It might not be a valid folder settings file..
        /// </summary>
        internal static string Error_NotValidFolderSettings {
            get {
                return ResourceManager.GetString("Error_NotValidFolderSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to read this template file. It might not be a valid template file..
        /// </summary>
        internal static string Error_NotValidTemplate {
            get {
                return ResourceManager.GetString("Error_NotValidTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified path (“{0}”) doesn&apos;t exist..
        /// </summary>
        internal static string Error_PathDoesNotExist {
            get {
                return ResourceManager.GetString("Error_PathDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error_Title {
            get {
                return ResourceManager.GetString("Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you would like to delete the folder settings for this directory? This action cannot be undone..
        /// </summary>
        internal static string FolderSettingsRemovalConfirm {
            get {
                return ResourceManager.GetString("FolderSettingsRemovalConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icon_About {
            get {
                object obj = ResourceManager.GetObject("Icon_About", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icon_Cache {
            get {
                object obj = ResourceManager.GetObject("Icon_Cache", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icon_CacheColor {
            get {
                object obj = ResourceManager.GetObject("Icon_CacheColor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icon_CacheList {
            get {
                object obj = ResourceManager.GetObject("Icon_CacheList", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icon_FixBorders {
            get {
                object obj = ResourceManager.GetObject("Icon_FixBorders", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icon_FolderSettings {
            get {
                object obj = ResourceManager.GetObject("Icon_FolderSettings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icon_Minus {
            get {
                object obj = ResourceManager.GetObject("Icon_Minus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icon_Plus {
            get {
                object obj = ResourceManager.GetObject("Icon_Plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icon_Settings {
            get {
                object obj = ResourceManager.GetObject("Icon_Settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icon_Template {
            get {
                object obj = ResourceManager.GetObject("Icon_Template", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kataraktaCS_logo {
            get {
                object obj = ResourceManager.GetObject("kataraktaCS_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced, real-time texture editor for SM64 machinimas..
        /// </summary>
        internal static string m64mm_desc {
            get {
                return ResourceManager.GetString("m64mm_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open kataraktaCS.
        /// </summary>
        internal static string m64mm_open {
            get {
                return ResourceManager.GetString("m64mm_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Template.
        /// </summary>
        internal static string NewTemplate {
            get {
                return ResourceManager.GetString("NewTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Texture.
        /// </summary>
        internal static string NewTexture {
            get {
                return ResourceManager.GetString("NewTexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .png file (*.png)|*.png.
        /// </summary>
        internal static string Quad64SaveSelectExtension {
            get {
                return ResourceManager.GetString("Quad64SaveSelectExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select where you would like to save the texture.
        /// </summary>
        internal static string Quad64SaveTitle {
            get {
                return ResourceManager.GetString("Quad64SaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Refresh {
            get {
                object obj = ResourceManager.GetObject("Refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm removal.
        /// </summary>
        internal static string RemovalConfirmTitle {
            get {
                return ResourceManager.GetString("RemovalConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Search {
            get {
                object obj = ResourceManager.GetObject("Search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segment.
        /// </summary>
        internal static string Segment {
            get {
                return ResourceManager.GetString("Segment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double-click here to insert name.
        /// </summary>
        internal static string Settings_InsertGameNameHere {
            get {
                return ResourceManager.GetString("Settings_InsertGameNameHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the “hires_texture” folder in your emulator.
        /// </summary>
        internal static string Settings_SelectHiResPath {
            get {
                return ResourceManager.GetString("Settings_SelectHiResPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another template already exists with this filename. Please pick another filename..
        /// </summary>
        internal static string TemplateFilenameAlreadyExistsError {
            get {
                return ResourceManager.GetString("TemplateFilenameAlreadyExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified template “{0}” does not seem to exist..
        /// </summary>
        internal static string TemplatePathDoesNotExist {
            get {
                return ResourceManager.GetString("TemplatePathDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you would like to delete the selected template? This action cannot be undone..
        /// </summary>
        internal static string TemplateRemovalConfirm {
            get {
                return ResourceManager.GetString("TemplateRemovalConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you would like to remove the selected texture?.
        /// </summary>
        internal static string TextureRemovalConfirm {
            get {
                return ResourceManager.GetString("TextureRemovalConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative filename: “{0}”.
        /// </summary>
        internal static string TextureToolTip_AlternativeFilename {
            get {
                return ResourceManager.GetString("TextureToolTip_AlternativeFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display: {0}.
        /// </summary>
        internal static string TextureToolTip_Display {
            get {
                return ResourceManager.GetString("TextureToolTip_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string TextureToolTip_No {
            get {
                return ResourceManager.GetString("TextureToolTip_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No alternative filename.
        /// </summary>
        internal static string TextureToolTip_NoAlternativeFilename {
            get {
                return ResourceManager.GetString("TextureToolTip_NoAlternativeFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No texture pack filename.
        /// </summary>
        internal static string TextureToolTip_NoTexturePackFilename {
            get {
                return ResourceManager.GetString("TextureToolTip_NoTexturePackFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Used).
        /// </summary>
        internal static string TextureToolTip_PathIsUsed {
            get {
                return ResourceManager.GetString("TextureToolTip_PathIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAM address: {0}.
        /// </summary>
        internal static string TextureToolTip_RAMAddress {
            get {
                return ResourceManager.GetString("TextureToolTip_RAMAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAM format: {0}.
        /// </summary>
        internal static string TextureToolTip_RAMFormat {
            get {
                return ResourceManager.GetString("TextureToolTip_RAMFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture pack filename: “{0}”.
        /// </summary>
        internal static string TextureToolTip_TexturePackFilename {
            get {
                return ResourceManager.GetString("TextureToolTip_TexturePackFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title: “{0}”.
        /// </summary>
        internal static string TextureToolTip_Title {
            get {
                return ResourceManager.GetString("TextureToolTip_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string TextureToolTip_Yes {
            get {
                return ResourceManager.GetString("TextureToolTip_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking….
        /// </summary>
        internal static string updates_checking_string {
            get {
                return ResourceManager.GetString("updates_checking_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap updates_latest {
            get {
                object obj = ResourceManager.GetObject("updates_latest", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up-to-date.
        /// </summary>
        internal static string updates_latest_string {
            get {
                return ResourceManager.GetString("updates_latest_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap updates_outdated {
            get {
                object obj = ResourceManager.GetObject("updates_outdated", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update available!.
        /// </summary>
        internal static string updates_outdated_string {
            get {
                return ResourceManager.GetString("updates_outdated_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap updates_refresh {
            get {
                object obj = ResourceManager.GetObject("updates_refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap updates_unknown {
            get {
                object obj = ResourceManager.GetObject("updates_unknown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not check if you have the latest version.
        ///
        ///Possible reasons:
        ///• The add-on has no access to the internet.
        ///• You&apos;ve checked for updates too frequently (can lead to temporarily exceeding GitHub&apos;s API rate limit).
        ///
        ///Would you like to open the latest release&apos;s page on GitHub in your browser?.
        /// </summary>
        internal static string updates_unknown_elaborate {
            get {
                return ResourceManager.GetString("updates_unknown_elaborate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t check for updates.
        /// </summary>
        internal static string updates_unknown_string {
            get {
                return ResourceManager.GetString("updates_unknown_string", resourceCulture);
            }
        }
    }
}
